/*
 * SocialProofSection — Testimonials and key workflow highlight
 * Design: Bioluminescent Dark Science
 * - Quotes from clinicians
 * - Workflow highlight bar
 */
import FadeIn from "@/components/FadeIn";

const testimonials = [
  {
    quote:
      "AxonAI reduced our gait assessment time from 45 minutes to under 5 minutes. The objectivity of the reports improved dramatically, and our therapists' workload has decreased noticeably.",
    author: "Head of Rehabilitation, NHS Trust",
    role: "Neurological Rehabilitation · Consultant Physician",
    color: "#00D4AA",
  },
  {
    quote:
      "The personalised plans generated by the system align closely with our clinical experience, and the ability to track patient progress in real time has been invaluable for improving adherence.",
    author: "Senior Physiotherapist",
    role: "Rehabilitation Therapist · 10 Years Clinical Experience",
    color: "#8B5CF6",
  },
  {
    quote:
      "As a department manager, AxonAI gave me the ability to evaluate treatment outcomes with data for the first time — providing an objective basis for resource allocation and performance review.",
    author: "Director, Rehabilitation Centre",
    role: "Healthcare Institution Administrator",
    color: "#00A8FF",
  },
];

export default function SocialProofSection() {
  return (
    <section
      className="relative py-24 overflow-hidden"
      style={{ background: "oklch(0.08 0.022 248)" }}
    >
      {/* Background accent */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          backgroundImage:
            "radial-gradient(circle at 20% 50%, rgba(0, 212, 170, 0.04) 0%, transparent 50%), radial-gradient(circle at 80% 50%, rgba(139, 92, 246, 0.04) 0%, transparent 50%)",
        }}
      />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <FadeIn className="text-center mb-14">
          <p className="section-label mb-4">TESTIMONIALS</p>
          <h2
            className="text-3xl sm:text-4xl font-bold"
            style={{
              fontFamily: "'Sora', sans-serif",
              color: "oklch(0.93 0.005 250)",
            }}
          >
            Voices from the Clinical Front Line
          </h2>
        </FadeIn>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {testimonials.map((t, i) => (
            <FadeIn key={i} delay={i * 120}>
              <div
                className="p-7 rounded-2xl h-full flex flex-col"
                style={{
                  background: "oklch(0.10 0.018 250)",
                  border: `1px solid ${t.color}20`,
                }}
              >
                {/* Quote mark */}
                <div
                  className="text-5xl font-black leading-none mb-4 select-none"
                  style={{
                    color: `${t.color}30`,
                    fontFamily: "'Sora', sans-serif",
                  }}
                >
                  "
                </div>

                <p
                  className="text-sm leading-relaxed flex-1 mb-6"
                  style={{ color: "oklch(0.68 0.015 250)" }}
                >
                  {t.quote}
                </p>

                <div className="flex items-center gap-3">
                  <div
                    className="w-10 h-10 rounded-xl flex items-center justify-center text-xs font-bold flex-shrink-0"
                    style={{
                      background: `${t.color}15`,
                      border: `1px solid ${t.color}25`,
                      color: t.color,
                      fontFamily: "'Sora', sans-serif",
                    }}
                  >
                    {t.author.charAt(0)}
                  </div>
                  <div>
                    <p
                      className="text-sm font-semibold"
                      style={{
                        fontFamily: "'Sora', sans-serif",
                        color: "oklch(0.85 0.005 250)",
                      }}
                    >
                      {t.author}
                    </p>
                    <p
                      className="text-xs"
                      style={{ color: "oklch(0.5 0.015 250)" }}
                    >
                      {t.role}
                    </p>
                  </div>
                </div>
              </div>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  );
}
