// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/configure": {
    params: {};
  };
  "/report": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/configure" | "/report" | "/*";
  };
  "routes/[configure]._index.jsx": {
    id: "routes/[configure]._index";
    page: "/configure";
  };
  "routes/[report]._index.jsx": {
    id: "routes/[report]._index";
    page: "/report";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[configure]._index": typeof import("./app/routes/[configure]._index.jsx");
  "routes/[report]._index": typeof import("./app/routes/[report]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};